# Generated by Django 6.0.3 on 2026-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverystop",
            name="product_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="deliverystop",
            name="recipient_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="deliverystop",
            name="recipient_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
