# Generated by Django 6.0.3 on 2026-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_deliverysession_owner_sharedroute_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="deliverysession",
            name="total_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverysession",
            name="total_duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
