# Generated by Django 6.0.3 on 2026-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0005_add_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="route_geometry",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
