# Generated by Django 6.0.3 on 2026-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_add_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='route_segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
