# Generated by Django 6.0.3 on 2026-04-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0007_add_route_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_routes",
                to="planner.deliverysession",
            ),
        ),
        migrations.AlterField(
            model_name="deliverysession",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                    ("split", "Split into Routes"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
