# Generated by Django 6.0.3 on 2026-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0008_session_parent_and_split_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverysession",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                    ("split", "Split into Routes"),
                ],
                db_index=True,
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliverystop",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("not_received", "Not Received"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliverystop",
            name="geocode_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliverystop",
            name="sequence_order",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
